parameters:
    app.allowed_email_domains: '%env(string:ALLOWED_EMAIL_DOMAINS)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Controller\AuthController:
        arguments:
            $allowedEmailDomains: '%app.allowed_email_domains%'
