parameters:
    app.mailer_from: '%env(string:MAILER_FROM)%'
    app.reservation.timezone: '%env(string:APP_TIMEZONE)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Controller\AuthController:
        arguments:
            $mailerFrom: '%app.mailer_from%'

    App\Service\ReservationPolicy:
        arguments:
            $timezone: '%app.reservation.timezone%'
