framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false
    handle_all_throwables: true
    php_errors:
        log: true
    session:
        cookie_lifetime: 604800
        gc_maxlifetime: 604800
        cookie_samesite: lax
    mailer:
        dsn: '%env(MAILER_DSN)%'
